const TAG = 'SPEN_'

export const SPENDING_REQUESTED = 'SPENDING_REQUESTED';
export const SPENDING_SUCCESS = 'SPENDING_SUCCESS';
export const SPENDING_FAILURE = 'SPENDING_FAILURE';
export const SET_SPENDING_LIMIT_SUCCESS = 'SET_SPENDING_LIMIT_SUCCESS';

export const RESET_SPENDING_LIMIT_SUCCESS = 'RESET_SPENDING_LIMIT_SUCCESS';



