const TAG = 'GLOB_'
export const API_LOADING_START = TAG + 'API_LOADING_START';
export const API_LOADING_STOP = TAG + 'API_LOADING_STOP';
export const IS_INTERNET_CONNECTED = TAG + 'IS_INTERNET_CONNECTED';
export const ON_ERROR_RECEIVED = TAG + 'ON_ERROR_RECEIVED';


export const CONTANT_API_LOADING_START = TAG + 'CONTANT_API_LOADING_START';
export const CONTANT_API_LOADING_STOP = TAG + 'CONTANT_API_LOADING_STOP';

export const CONFIG_SUCCESS = TAG + 'CONFIG_SUCCESS';
export const CONFIG_ERROR = TAG + 'CONFIG_ERROR';
export const SET_CURRENT_ROUTE_NAME = 'SET_CURRENT_ROUTE_NAME';
export const SET_CURRENT_LANGUAGE ='SET_CURRENT_LANGUAGE';

export const CRIPTO_DETAIL_REQUESTED = 'CRIPTO_DETAIL_REQUESTED';
export const CRIPTO_DETAIL_SUCCESS = 'CRIPTO_DETAIL_SUCCESS';
export const CRIPTO_DETAIL_FAILURE = 'CRIPTO_DETAIL_FAILURE';



