const TAG = 'GLOB_'
export const API_LOADING_START = TAG + 'API_LOADING_START';
export const API_LOADING_STOP = TAG + 'API_LOADING_STOP';
export const SET_CURRENT_ROUTE_NAME = 'SET_CURRENT_ROUTE_NAME';
export const IS_INTERNET_CONNECTED = TAG + 'IS_INTERNET_CONNECTED';



